%% 3.1 | 3 månaders bindningstid
%
function tre_ett
%% Beräkningar
a_start = input('Hur stort är ditt startkapital? ');
    if isempty(a_start)
        a_start = 0;
    end
a_spar = input('Hur mycket ska du spara per 3-månader period: ');
    if isempty(a_spar)
        a_spar = 300; % Trehundra kr per månad.
    end
a_ranta = input('Ränta per varje 3-månader period (%): '); % Detta är årsräntan.
a_ranta = a_ranta / 100; % För att få fram procenten.
    if isempty(a_ranta)
        a_ranta = 0.6 / 100;
    end
a_tid = input('Antal 3-månader perioder: ');
    if isempty(a_tid)
        a_tid = 8; % Två år.
    end

a_tot = zeros( a_tid, 4); % Skapar hela matrisen.
a_tot(1, 1) = a_start; % Räknar ut det första elementet. Totala kapitalet.
a_tot(1, 2) = a_start; % Räknar ut det första elementet. Kapitalet utan avkastningen.
a_tot(1, 3) = a_tot(1, 1) - a_tot(1, 2); % Räknar ut det första elementet. Endast avkastningen.
a_tot(1, 4) = (a_tot(1, 3) / a_tot(1, 1)) * 100; % Räknar ut det första elementet. Hur stor del avkastningen är i %.
    for i_1 = 2: (a_tid + 1)
        a_tot(i_1, 1) = a_tot( (i_1 - 1), 1) + a_tot( (i_1 - 1), 1) * (a_ranta/12) + a_spar; % Räntan betalas ut per månad
        % Denna kolumn räknar ut det totala kapitalet efter varje period.
        a_tot(i_1, 2) = a_tot( (i_1 - 1), 2) + a_spar;
        % Denna kolumn räknar ut kapitalet utan avkastning.
        a_tot(i_1, 3) = a_tot(i_1, 1) - a_tot(i_1, 2);
        % Denna kolumn räknar ut endast avkastningen.
        a_tot(i_1, 4) = (a_tot(i_1, 3) / a_tot(i_1, 1)) * 100;
        % Denna kolumn räknar ut hur stor del (%) avkastningen är.
    end
%% Plots
hFigure_1 = figure;
set(hFigure_1, ...
    'Name', '3 månaders bindningstid', ... 
    'Units', 'Pixels', ...
    'Position', [150 100 1200 800] );

hold on;
% Subplot 1
subplot(1, 2, 1);
hold on; % Behövs när det en subplot
hLine_1 = line( 0:a_tid, a_tot(:, 1) ); % Plottar tiden i mån och kol 1.

set(hLine_1, ...
    'LineStyle', ':', ... % In latest MATLAB ".-" is an error
    'LineWidth', 2, ...
    'Marker', 'o', ...
    'MarkerSize', 6, ...
    'Color', 'red', ...
    'MarkerEdgeColor', [.2 .2 .2], ...
    'MarkerFaceColor', [.7 .7 .7] );

hTitle_1 = title(['Månadssparande: ' num2str(a_spar) ' kr i ' num2str(a_tid*3) ' månader']);
hXLabel_1 = xlabel('Antal 3-månader perioder');
hYLabel_1 = ylabel('Kapital (kr)');

hLegend_1 = legend(hLine_1, ...
    'Kapital med avkastning', ...
    'Location', 'NorthWest');

set(gca, ...
    'FontName', 'Helvetica');

set( [hTitle_1, hXLabel_1, hYLabel_1], ...
    'FontName', 'AvantGarde');

set( [hLegend_1, gca], ...
    'FontSize', 8);

set( [hXLabel_1, hYLabel_1], ...
    'FontSize', 10);

set(hTitle_1, ...
    'FontSize', 12, ...
    'FontWeight', 'light');

set(gca, ...
    'Box', 'off', ...
    'TickDir', 'out', ...
    'TickLength', [.02 .02], ...
    'XMinorTick', 'on', ...
    'YMinorTick', 'on', ...
    'YGrid', 'on', ...
    'XColor', [.3 .3 .3], ...
    'YColor', [.3 .3 .3], ...
    'YTickMode', 'auto', ...
    'LineWidth', 2, ...
    'XTickMode', 'auto');
% Subplot 2
subplot(1, 2, 2);
hold on;
hLine_2 = line( 0:a_tid, a_tot(:, 3) ); % Plottar tiden i mån och kol 2.

set(hLine_2, ...
    'LineStyle', ':', ... % In latest MATLAB ".-" is an error
    'LineWidth', 2, ...
    'Marker', 'o', ...
    'MarkerSize', 6, ...
    'Color', 'blue', ...
    'MarkerEdgeColor', [.2 .2 .2], ...
    'MarkerFaceColor', [.7 .7 .7] );

hTitle_2 = title(['Månadssparande: ' num2str(a_spar) ' kr i ' num2str(a_tid*3) ' månader']);
hXLabel_2 = xlabel('Antal 3-månader perioder');
hYLabel_2 = ylabel('Avkastning (kr)');

hLegend_2 = legend(hLine_2, ...
    'Endast avkastning', ...
    'Location', 'NorthWest');

set(gca, ...
    'FontName', 'Helvetica');

set( [hTitle_2, hXLabel_2, hYLabel_2], ...
    'FontName', 'AvantGarde');

set( [hLegend_2, gca], ...
    'FontSize', 8);

set( [hXLabel_2, hYLabel_2], ...
    'FontSize', 10);

set(hTitle_2, ...
    'FontSize', 12, ...
    'FontWeight', 'light');

set(gca, ...
    'Box', 'off', ...
    'TickDir', 'out', ...
    'TickLength', [.02 .02], ...
    'XMinorTick', 'on', ...
    'YMinorTick', 'on', ...
    'YGrid', 'on', ...
    'XColor', [.3 .3 .3], ...
    'YColor', [.3 .3 .3], ...
    'YTickMode', 'auto', ...
    'LineWidth', 2, ...
    'XTickMode', 'auto');

hold off; % Behövs när det är en subplot.
hold off;
%% Sparande av figur
% PATH_part_1 = '...\Pics\';
% PATH_part_2 = input('Hur vill du namnge grafen? ', 's');
% PATH_part_3 = '_jpeg';
% PATH = [PATH_part_1, PATH_part_2, PATH_part_3];
% %set(gcf, 'PaperPositionMode', 'auto');
% imwrite(gcf, PATH, 'jpeg');
end

%% Kommentarer
% Plots formateringen är inte klar.
    % Lägg till så den sparar grafen som jpg.
	% Lägg till en annotering "avkastnings procent" a_tot(end, 4)