%% 3.5 Ingen bindningstid
%
function tre_fem
%% Beräkningar
e_start = input('Hur stort är ditt startkapital? ');
    if isempty(e_start)
        e_start = 0;
    end
e_spar = input('Hur mycket kommer du spara per månad? ');
    if isempty(e_spar)
        e_spar = 300; % Trehundra kr per månad.
    end
e_ranta = input('Hur stor är räntan? (%) '); % Detta är årsräntan.
e_ranta = e_ranta / 100; % För att få fram procenten.
    if isempty(e_ranta)
        e_ranta = 0.6 / 100;
    end
e_tid = input('Hur länge vill du spara (mån) ');
    if isempty(e_tid)
        e_tid = 24; % Två år.
    end
    
e_tot = zeros( e_tid, 4); % Skapar hela matrisen.
e_tot(1, 1) = e_start; % Räknar ut det första elementet. Totala kapitalet.
e_tot(1, 2) = e_start; % Räknat ut det första elementet. Kapitalet utan avkastningen.
e_tot(1, 3) = e_tot(1, 1) - e_tot(1, 2); % Räknat ut det första elementet. Endast avkastningen.
e_tot(1, 4) = (e_tot(1, 3) / e_tot(1, 1)) * 100; % Räknat ut det första elementet. Hur stor del avkastningen är i %.
    for i_1 = 2: (e_tid + 1)
        e_tot(i_1, 1) = e_tot( (i_1 - 1), 1) + e_tot( (i_1 - 1), 1) * (e_ranta/12) + e_spar; % Räntan betalas ut per månad
        % Denna kolumn räknar ut det totala kapitalet efter varje period.
        e_tot(i_1, 2) = e_tot( (i_1 - 1), 2) + e_spar;
        % Denna kolumn räknar ut kapitalet utan avkastning.
        e_tot(i_1, 3) = e_tot(i_1, 1) - e_tot(i_1, 2);
        % Denna kolumn räknar ut endast avkastningen.
        e_tot(i_1, 4) = (e_tot(i_1, 3) / e_tot(i_1, 1)) * 100;
        % Denna kolumn räknar ut hur stor del (%) avkastningen är.
    end
%% Plots
hFigure_1 = figure;
set(hFigure_1, ...
    'Name', '24 månaders bindningstid', ... 
    'Units', 'Pixels', ...
    'Position', [150 100 1200 800] );

hold on;
% Subplot 1
subplot(1, 2, 1);
hold on; % Behövs när det en subplot
hLine_1 = line( 0:e_tid, e_tot(:, 1) ); % Plottar tiden i mån och kol 1.

set(hLine_1, ...
    'LineStyle', ':', ... % In latest MATLAB ".-" is an error
    'LineWidth', 2, ...
    'Marker', 'o', ...
    'MarkerSize', 6, ...
    'Color', 'red', ...
    'MarkerEdgeColor', [.2 .2 .2], ...
    'MarkerFaceColor', [.7 .7 .7] );

hTitle_1 = title(['Månadssparande: ' num2str(e_spar) ' kr i ' num2str(e_tid) ' månader']);
hXLabel_1 = xlabel('Antal månader');
hYLabel_1 = ylabel('Kapital (kr)');

hLegend_1 = legend(hLine_1, ...
    'Kapital med avkastning', ...
    'Location', 'NorthWest');

set(gca, ...
    'FontName', 'Helvetica');

set( [hTitle_1, hXLabel_1, hYLabel_1], ...
    'FontName', 'AvantGarde');

set( [hLegend_1, gca], ...
    'FontSize', 8);

set( [hXLabel_1, hYLabel_1], ...
    'FontSize', 10);

set(hTitle_1, ...
    'FontSize', 12, ...
    'FontWeight', 'light');

set(gca, ...
    'Box', 'off', ...
    'TickDir', 'out', ...
    'TickLength', [.02 .02], ...
    'XMinorTick', 'on', ...
    'YMinorTick', 'on', ...
    'YGrid', 'on', ...
    'XColor', [.3 .3 .3], ...
    'YColor', [.3 .3 .3], ...
    'YTickMode', 'auto', ...
    'LineWidth', 2, ...
    'XTickMode', 'auto');
% Subplot 2
subplot(1, 2, 2);
hold on;
hLine_2 = line( 0:e_tid, e_tot(:, 3) ); % Plottar tiden i mån och kol 2.

set(hLine_2, ...
    'LineStyle', ':', ... % In latest MATLAB ".-" is an error
    'LineWidth', 2, ...
    'Marker', 'o', ...
    'MarkerSize', 6, ...
    'Color', 'blue', ...
    'MarkerEdgeColor', [.2 .2 .2], ...
    'MarkerFaceColor', [.7 .7 .7] );

hTitle_2 = title(['Månadssparande: ' num2str(e_spar) ' kr i ' num2str(e_tid) ' månader']);
hXLabel_2 = xlabel('Antal månader');
hYLabel_2 = ylabel('Avkastning (kr)');

hLegend_2 = legend(hLine_2, ...
    'Endast avkastning', ...
    'Location', 'NorthWest');

set(gca, ...
    'FontName', 'Helvetica');

set( [hTitle_2, hXLabel_2, hYLabel_2], ...
    'FontName', 'AvantGarde');

set( [hLegend_2, gca], ...
    'FontSize', 8);

set( [hXLabel_2, hYLabel_2], ...
    'FontSize', 10);

set(hTitle_2, ...
    'FontSize', 12, ...
    'FontWeight', 'light');

set(gca, ...
    'Box', 'off', ...
    'TickDir', 'out', ...
    'TickLength', [.02 .02], ...
    'XMinorTick', 'on', ...
    'YMinorTick', 'on', ...
    'YGrid', 'on', ...
    'XColor', [.3 .3 .3], ...
    'YColor', [.3 .3 .3], ...
    'YTickMode', 'auto', ...
    'LineWidth', 2, ...
    'XTickMode', 'auto');

hold off; % Behövs när det är en subplot.
hold off;
%% Sparande av figur

end

%% Kommentarer
% Lägg till plottar