%% 3.2 6 månaders bindningstid
%
function tre_tva
%% Beräkningar
b_start = input('Hur stort är ditt startkapital? ');
    if isempty(b_start)
        b_start = 0;
    end
b_spar = input('Sparande per varje 6-månader period: ');
    if isempty(b_spar)
        b_spar = 300; % Trehundra kr per månad.
    end
b_ranta = input('Ränta per varje 6-månader period (%): '); % Detta är årsräntan.
b_ranta = b_ranta / 100; % För att få fram procenten.
    if isempty(b_ranta)
        b_ranta = 0.8 / 100;
    end
b_tid = input('Antal 6-månader perioder: ');
    if isempty(b_tid)
        b_tid = 4; % Två år.
    end
    
b_tot = zeros( b_tid, 4); % Skapar hela matrisen.
b_tot(1, 1) = b_start; % Räknar ut det första elementet. Totala kapitalet.
b_tot(1, 2) = b_start; % Räknar ut det första elementet. Kapitalet utan avkastningen.
b_tot(1, 3) = b_tot(1, 1) - b_tot(1, 2); % Räknar ut det första elementet. Endast avkastningen.
b_tot(1, 4) = (b_tot(1, 3) / b_tot(1, 1)) * 100; % Räknar ut det första elementet. Hur stor del avkastningen är.
    for i_1 = 2: (b_tid + 1)
        b_tot(i_1, 1) = b_tot( (i_1 - 1), 1) + b_tot( (i_1 - 1), 1) * (b_ranta/12) + b_spar; % Räntan betalas ut per månad
        % Denna kolumn räknar ut det totala kapitalet efter varje period.
        b_tot(i_1, 2) = b_tot( (i_1 - 1), 2) + b_spar;
        % Denna kolumn räknar ut kapitalet utan avkastning.
        b_tot(i_1, 3) = b_tot(i_1, 1) - b_tot(i_1, 2);
        % Denna kolumn räknar ut endast avkastningen.
        b_tot(i_1, 4) = (b_tot(i_1, 4) / b_tot(i_1, 1)) * 100;
        % Denna kolumn räknar ut hur stor del (%) avkastningen är.
    end
%% Plots
hFigure_1 = figure;
set(hFigure_1, ...
    'Name', '6 månaders bindningstid', ... 
    'Units', 'Pixels', ...
    'Position', [150 100 1200 800] );

hold on;
% Subplot 1
subplot(1, 2, 1);
hold on; % Behövs när det en subplot
hLine_1 = line( 0:b_tid, b_tot(:, 1) ); % Plottar tiden i mån och kol 1.

set(hLine_1, ...
    'LineStyle', ':', ... % In latest MATLAB ".-" is an error
    'LineWidth', 2, ...
    'Marker', 'o', ...
    'MarkerSize', 6, ...
    'Color', 'red', ...
    'MarkerEdgeColor', [.2 .2 .2], ...
    'MarkerFaceColor', [.7 .7 .7] );

hTitle_1 = title(['Månadssparande: ' num2str(b_spar) ' kr i ' num2str(b_tid*6) ' månader']);
hXLabel_1 = xlabel('Antal 6-månader perioder');
hYLabel_1 = ylabel('Kapital (kr)');

hLegend_1 = legend(hLine_1, ...
    'Kapital med avkastning', ...
    'Location', 'NorthWest');

set(gca, ...
    'FontName', 'Helvetica');

set( [hTitle_1, hXLabel_1, hYLabel_1], ...
    'FontName', 'AvantGarde');

set( [hLegend_1, gca], ...
    'FontSize', 8);

set( [hXLabel_1, hYLabel_1], ...
    'FontSize', 10);

set(hTitle_1, ...
    'FontSize', 12, ...
    'FontWeight', 'light');

set(gca, ...
    'Box', 'off', ...
    'TickDir', 'out', ...
    'TickLength', [.02 .02], ...
    'XMinorTick', 'on', ...
    'YMinorTick', 'on', ...
    'YGrid', 'on', ...
    'XColor', [.3 .3 .3], ...
    'YColor', [.3 .3 .3], ...
    'YTickMode', 'auto', ...
    'LineWidth', 2, ...
    'XTickMode', 'auto');
% Subplot 2
subplot(1, 2, 2);
hold on;
hLine_2 = line( 0:b_tid, b_tot(:, 3) ); % Plottar tiden i mån och kol 2.

set(hLine_2, ...
    'LineStyle', ':', ... % In latest MATLAB ".-" is an error
    'LineWidth', 2, ...
    'Marker', 'o', ...
    'MarkerSize', 6, ...
    'Color', 'blue', ...
    'MarkerEdgeColor', [.2 .2 .2], ...
    'MarkerFaceColor', [.7 .7 .7] );

hTitle_2 = title(['Månadssparande: ' num2str(b_spar) ' kr i ' num2str(b_tid*6) ' månader']);
hXLabel_2 = xlabel('Antal 6-månader perioder');
hYLabel_2 = ylabel('Avkastning (kr)');

hLegend_2 = legend(hLine_2, ...
    'Endast avkastning', ...
    'Location', 'NorthWest');

set(gca, ...
    'FontName', 'Helvetica');

set( [hTitle_2, hXLabel_2, hYLabel_2], ...
    'FontName', 'AvantGarde');

set( [hLegend_2, gca], ...
    'FontSize', 8);

set( [hXLabel_2, hYLabel_2], ...
    'FontSize', 10);

set(hTitle_2, ...
    'FontSize', 12, ...
    'FontWeight', 'light');

set(gca, ...
    'Box', 'off', ...
    'TickDir', 'out', ...
    'TickLength', [.02 .02], ...
    'XMinorTick', 'on', ...
    'YMinorTick', 'on', ...
    'YGrid', 'on', ...
    'XColor', [.3 .3 .3], ...
    'YColor', [.3 .3 .3], ...
    'YTickMode', 'auto', ...
    'LineWidth', 2, ...
    'XTickMode', 'auto');

hold off; % Behövs när det är en subplot.
hold off;
%% Sparande av figur

end

%% Kommentarer
%